# Generated by Django 3.0.8 on 2020-08-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200825_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='proudct_name',
            new_name='product_name',
        ),
    ]
