# Generated by Django 3.0.8 on 2020-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200825_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=70)),
                ('Desc', models.CharField(default='', max_length=2000)),
                ('Phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_desc',
            field=models.CharField(max_length=2000),
        ),
    ]
